export const colors = {
    light: {
        background: "#FDFDFD",
        background2: "#fff",
        primary: '#7472E0',
        primary2: '#7F22FD',
        tertiary: "#4B4B4B",
        bg_switch: "#e3e3e3",
        switch_on: "#BB86FC",
        tint: "#111827",
        text: "#111827",
        heading1: "#FDFDFD",
        text_sub: "gray",
        img: "#fff",
        category: "#3DB9F7",
    },
    dark: {
        background: "#121212",
        background2: "#000",
        primary: '#BB86FC',
        primary2: '#7F22FD',
        tertiary: "#f9fafb",
        bg_switch: "#664B86",
        switch_on: "#BB86FC",
        text: "#E3E3E3",
        heading1: "#FDFDFD",
        text_sub: "#D8D8D8",
        tint: "#f9fafb",
        img: "#f9fafb",
        category: "#3DB9F7",
    },
};
