export const colors = {
    light: {
        background: "#F7F7F7",
        background2: "#fff",
        background_button: '#2DD35C',
        primary: '#7472E0',
        primary2: '#7F22FD',
        tertiary: "#4B4B4B",
        bg_switch: "#e3e3e3",
        switch_on: "#BB86FC",
        text: "#111827",
        text2: "#000",
        heading1: "#FDFDFD",
        text_sub: "gray",
    },
    dark: {
        background: "#121212",
        background2: "#000",
        background_button: '#2DD35C',
        primary: '#BB86FC',
        primary2: '#7F22FD',
        tertiary: "#f9fafb",
        bg_switch: "#664B86",
        switch_on: "#BB86FC",
        text: "#E3E3E3",
        text2: "#fff",
        heading1: "#FDFDFD",
        text_sub: "#D8D8D8",
    },
};
